//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportProducts
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdvCat
    {
        public AdvCat()
        {
            this.AdvCatPermission = new HashSet<AdvCatPermission>();
            this.AdvCats1 = new HashSet<AdvCat>();
            this.CAT_AdvCatProducts = new HashSet<AdvCatProduct>();
        }
    
        public int AdvCatID { get; set; }
        public int AdvCatOrder { get; set; }
        public Nullable<int> PortalID { get; set; }
        public string AdvCatName { get; set; }
        public bool IsVisible { get; set; }
        public Nullable<int> ParentId { get; set; }
        public bool DisableLink { get; set; }
        public string Url { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string KeyWords { get; set; }
        public bool IsDeleted { get; set; }
        public string IconFile { get; set; }
        public int Level { get; set; }
        public string AdvCatImportID { get; set; }
    
        public virtual ICollection<AdvCatPermission> AdvCatPermission { get; set; }
        public virtual ICollection<AdvCat> AdvCats1 { get; set; }
        public virtual AdvCat AdvCats2 { get; set; }
        public virtual ICollection<AdvCatProduct> CAT_AdvCatProducts { get; set; }
    }
}
