//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportProducts
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdvCatProduct
    {
        public int AdvCatProductID { get; set; }
        public int AdvCatID { get; set; }
        public int ProductID { get; set; }
        public Nullable<bool> AddAdvCatToProductDisplay { get; set; }
    
        public virtual AdvCat AdvCats { get; set; }
        public virtual Product Products { get; set; }
    }
}
