//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportProducts
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductImage
    {
        public ProductImage()
        {
            this.Description = "";
            this.ImageType = "0";
            this.ViewOrder = 0;
        }
    
        public int ImageID { get; set; }
        public int ProductID { get; set; }
        public string ImageURL { get; set; }
        public string ImageFile { get; set; }
        public string Description { get; set; }
        public string ImageType { get; set; }
        public Nullable<int> ViewOrder { get; set; }
    
        public virtual Product Products { get; set; }
    }
}
