//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportProducts
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.EAN = "";
            this.ISBN = "";
            this.Free1 = "";
            this.Free2 = "";
            this.Free3 = "";
            this.KeyWords = "";
            this.Stock = 0;
            this.OrderQuant = "";
            this.Weight = 0.0000m;
            this.Volume = 0.00m;
            this.Length = 0.00m;
            this.Width = 0.00m;
            this.Height = 0.00m;
            this.FreightCosts1 = 0.0000m;
            this.FreightCosts2 = 0.0000m;
            this.Featured = false;
            this.SalePrice = 0.0000m;
            this.SaleStart = new DateTime(646602048000000000, DateTimeKind.Unspecified);
            this.SaleEnd = new DateTime(599266080000000000, DateTimeKind.Unspecified);
            this.DownLoad = false;
            this.ZIPPassWord = "";
            this.DownLoadFile = "";
            this.Archive = false;
            this.CreatedByUser = 1;
            this.BulkPriceLimit1 = 0;
            this.BulkPriceLimit2 = 0;
            this.BulkPriceLimit3 = 0;
            this.BulkPriceLimit4 = 0;
            this.BulkPriceLimit5 = 0;
            this.RoleID = -1;
            this.SubscriptionPeriod = 0;
            this.RecurringBilling = false;
            this.TaxExempt = false;
            this.ShipExempt = false;
            this.InsuredValue = 0.0000m;
            this.PublicationStart = new DateTime(634538880000000000, DateTimeKind.Unspecified);
            this.PublicationEnd = new DateTime(650318976000000000, DateTimeKind.Unspecified);
            this.Status = "0";
            this.DonationItem = false;
            this.PayPalSubscription = false;
            this.UseRoleFees = false;
            this.ProductCost = 0m;
            this.RoleExpiryType = "0";
            this.ItemDeliveryType = "0";
            this.ReorderPoint = 0;
            this.OrderQuantValidExpr = "";
            this.ShippingAddress = "0";
            this.AuctionFinished = false;
            this.TaxCode = "";
            this.ProductImages = new HashSet<ProductImage>();
            this.CAT_AdvCatProducts = new HashSet<AdvCatProduct>();
        }
    
        public int ProductID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> Category2ID { get; set; }
        public string Category3 { get; set; }
        public string ProductName { get; set; }
        public string ProductNumber { get; set; }
        public string EAN { get; set; }
        public string ISBN { get; set; }
        public string Free1 { get; set; }
        public string Free2 { get; set; }
        public string Free3 { get; set; }
        public string KeyWords { get; set; }
        public string ProductImage { get; set; }
        public decimal UnitCost { get; set; }
        public Nullable<decimal> UnitCost2 { get; set; }
        public Nullable<decimal> UnitCost3 { get; set; }
        public Nullable<decimal> UnitCost4 { get; set; }
        public Nullable<decimal> UnitCost5 { get; set; }
        public Nullable<decimal> UnitCost6 { get; set; }
        public string Description { get; set; }
        public string DescriptionHTML { get; set; }
        public string URL { get; set; }
        public Nullable<int> Stock { get; set; }
        public string OrderQuant { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<decimal> Volume { get; set; }
        public Nullable<decimal> Length { get; set; }
        public Nullable<decimal> Width { get; set; }
        public Nullable<decimal> Height { get; set; }
        public Nullable<decimal> FreightCosts1 { get; set; }
        public Nullable<decimal> FreightCosts2 { get; set; }
        public bool Featured { get; set; }
        public decimal SalePrice { get; set; }
        public Nullable<System.DateTime> SaleStart { get; set; }
        public Nullable<System.DateTime> SaleEnd { get; set; }
        public Nullable<bool> DownLoad { get; set; }
        public string ZIPPassWord { get; set; }
        public string DownLoadFile { get; set; }
        public Nullable<bool> Archive { get; set; }
        public int CreatedByUser { get; set; }
        public int BulkPriceLimit1 { get; set; }
        public int BulkPriceLimit2 { get; set; }
        public int BulkPriceLimit3 { get; set; }
        public int BulkPriceLimit4 { get; set; }
        public int BulkPriceLimit5 { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> RoleID { get; set; }
        public Nullable<int> SubscriptionPeriod { get; set; }
        public Nullable<bool> RecurringBilling { get; set; }
        public Nullable<bool> TaxExempt { get; set; }
        public Nullable<bool> ShipExempt { get; set; }
        public decimal InsuredValue { get; set; }
        public Nullable<System.DateTime> PublicationStart { get; set; }
        public Nullable<System.DateTime> PublicationEnd { get; set; }
        public string Status { get; set; }
        public bool DonationItem { get; set; }
        public bool PayPalSubscription { get; set; }
        public bool UseRoleFees { get; set; }
        public decimal ProductCost { get; set; }
        public string RoleExpiryType { get; set; }
        public string ItemDeliveryType { get; set; }
        public int ReorderPoint { get; set; }
        public string OrderQuantValidExpr { get; set; }
        public string ShippingAddress { get; set; }
        public Nullable<int> OrigProductID { get; set; }
        public bool AuctionFinished { get; set; }
        public Nullable<decimal> StartingPrice { get; set; }
        public Nullable<decimal> ReservePrice { get; set; }
        public Nullable<int> LastModifiedByUserID { get; set; }
        public Nullable<System.DateTime> LastModifiedOnDate { get; set; }
        public string TaxCode { get; set; }
    
        public virtual ICollection<ProductImage> ProductImages { get; set; }
        public virtual ICollection<AdvCatProduct> CAT_AdvCatProducts { get; set; }
        public virtual Category CAT_Categories { get; set; }
    }
}
